### ISSUE TITLE
Node.js images

### ISSUE THREAD

**Issue by CalderWhite** [CalderWhite/Communication_Host#13]
Need to return images with our Node.js Server

**Comment by CalderWhite** [comment]
![edit - node html5 1](https://cloud.githubusercontent.com/assets/15067287/12877481/ec1c6a5a-cde1-11e5-9f8c-04b562633ee9.png)

**Comment by xerodragon72** [comment]
so you want me to add the image where?

**Comment by CalderWhite** [comment]
Please add it on the icon branch from master, then pull request and I'll check it over.

**Comment by CalderWhite** [comment]
Done, just changing now
